name: Benchmarks
on:
  push:
  pull_request:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Benchmarks
        run: npm install && FORCE_COLOR= node bench/run.js && echo ====== swap order ====== && FORCE_COLOR= node bench/run_swapped.js && echo ====== warmup ====== && FORCE_COLOR= node bench/run_warmup.js && echo ====== swap order again ====== && FORCE_COLOR= node bench/run_swapped_warmup.js
